In [93]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report

In [24]:
df = pd.read_csv('spam.csv',sep=',',encoding='latin-1')

In [25]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [18]:
len(df)

5575

In [26]:
len(df[df.v1=='spam'])

747

In [27]:
df.loc[df["v1"]=='ham',"v1"]=1
df.loc[df["v1"]=='spam',"v1"]=0

In [28]:
df.head()

v1                                                 v2 Unnamed: 2 Unnamed: 3  \
0  1  Go until jurong point, crazy.. Available only ...        NaN        NaN   
1  1                      Ok lar... Joking wif u oni...        NaN        NaN   
2  0  Free entry in 2 a wkly comp to win FA Cup fina...        NaN        NaN   
3  1  U dun say so early hor... U c already then say...        NaN        NaN   
4  1  Nah I don't think he goes to usf, he lives aro...        NaN        NaN   

  Unnamed: 4  
0        NaN  
1        NaN  
2        NaN  
3        NaN  
4        NaN

In [29]:
df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)

In [31]:
df = df.rename(columns={'v1': 'Status', 'v2': 'Message'})

In [32]:
df_x = df["Message"]
df_y = df["Status"]

In [33]:
df.head()

Status                                            Message
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...
2      0  Free entry in 2 a wkly comp to win FA Cup fina...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf, he lives aro...

In [34]:
df_x

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
5       FreeMsg Hey there darling it's been 3 week's n...
6       Even my brother is not like to speak with me. ...
7       As per your request 'Melle Melle (Oru Minnamin...
8       WINNER!! As a valued network customer you have...
9       Had your mobile 11 months or more? U R entitle...
10      I'm gonna be home soon and i don't want to tal...
11      SIX chances to win CASH! From 100 to 20,000 po...
12      URGENT! You have won a 1 week FREE membership ...
13      I've been searching for the right words to tha...
14                    I HAVE A DATE ON SUNDAY WITH WILL!!
15      XXXMobileMovieClub: To use your credit, click ...
16                             Oh k...i'm watching here:)
17      Eh u r

In [57]:
cv = TfidfVectorizer(min_df=1,stop_words='english')

In [99]:
x_train,x_test,y_train,y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [100]:
x_traincv =cv.fit_transform(["Hi,HOW ARE you,how are you doing","How you doing,wassup"])

In [101]:
x_traincv.toarray( )

array([[ 0.57973867,  0.81480247,  0.        ],
       [ 0.57973867,  0.        ,  0.81480247]])

In [102]:
cv.get_feature_names()

['doing', 'hi', 'wassup']

In [103]:
cv1 = TfidfVectorizer(min_df=1,stop_words="english")

In [104]:
x_traincv = cv1.fit_transform(x_train)

In [105]:
a = x_traincv.toarray()

In [106]:
a

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [107]:
len(a[0])

7425

In [108]:
cv1.inverse_transform(a[0])

[array(['09099725823', '2nite', 'borin', 'callså', 'chat', 'claire', 'cum',
        'havin', 'hope', 'luv', 'minmoremobsemspobox45po139wa', 'time',
        'wanna', 'xx'],
       dtype='<U34')]

In [109]:
x_train.iloc[0]

'CLAIRE here am havin borin time & am now alone U wanna cum over 2nite? Chat now 09099725823 hope 2 C U Luv CLAIRE xx Callså£1/minmoremobsEMSPOBox45PO139WA'

In [110]:
mnb= MultinomialNB()

In [111]:
y_train = y_train.astype('int')

In [112]:
 mnb.fit(x_traincv,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [113]:
x_testcv = cv1.transform(x_test)

In [114]:
pred = mnb.predict(x_testcv)

In [115]:
pred

array([1, 1, 0, ..., 1, 0, 0])

In [116]:
actual = np.array(y_test)

In [117]:
actual

array([1, 1, 0, ..., 1, 0, 0], dtype=object)

In [118]:
count = 0

In [119]:
 for i in range(len(pred)):
        if pred[i]==actual[i]:
            count=count+1

In [120]:
count

1079

In [121]:
len(pred)

1115

In [122]:
1068/1115

0.957847533632287

In [123]:
z = classification_report(actual,pred)

ValueError: Mix type of y not allowed, got types {'binary', 'unknown'}